### ISSUE TITLE
different results when I run with the same seed. 

### ISSUE THREAD

**Issue by slowbull** [D-X-Y/ResNeXt-DenseNet#5]
Hi, when I run with manualseed=1, I always get different results. Should I set torch.cuda.manual_seed_all(seed) in the model.py also, to make the results reproducible?

**Comment by D-X-Y** [comment]
Hi, I haven't checked manual_seed_all.
I think manualseed or manual_seed_all cannot control everything, because there might be something in cudnn or cublas use their own random seed? While you can control the initialization weights, and if you start training from the same initialization weights, you should get the similar performance.
